openapi: 3.1.0

info:
  title: Product API
  description: REST representation of Product GraphQL query
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          description: Unique product identifier
          schema:
            type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          description: Product ID
        name:
          type: string
          description: Product name
        price:
          type: string
          description: Product price
        description:
          type: string
          nullable: true
          description: Optional product description
